# Generated by Django 5.2.5 on 2025-09-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priceSale',
            new_name='productionPrice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productionSale',
            new_name='salePrice',
        ),
    ]
