# Generated by Django 5.2.5 on 2025-10-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adapteduser",
            name="birthDate",
            field=models.DateField(null=True),
        ),
    ]
