# Generated by Django 5.2.5 on 2025-11-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
    ]
