# Generated by Django 5.2.5 on 2025-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_adapteduser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('E', 'Entregue'), ('P', 'Pendente'), ('C', 'Cancelado')], default='P', max_length=1),
        ),
    ]
